version: '3'
services:
  mongo:
    container_name: 'mongo'
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
  app:
    env_file: .env
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    depends_on: 
      - mongo
    container_name: 'gazin-app'
    image: gazin-app
    ports:
      - "3000:3000"
  nettools:
    container_name: 'nettools'
    image: praqma/network-multitool
    ports:
      - "3030:3030"
