version: '3'
services:
  mongo:
    container_name: 'mongo'
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
    networks: 
      - app-network
  app:
    depends_on: 
      - mongo
    container_name: 'gazin-app'
    image: gazin-app
    ports:
      - "3000:3000"
    environment: 
      - MONGO_HOSTNAME=192.168.0.105
      - MONGO_PORT=27018
      - MONGO_DB=api-db-gazin
    networks: 
      - app-network
networks: 
  app-network:
    driver: bridge
